name: Analysis

on:
  push:
    paths-ignore:
      - 'doc/**'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - 'doc/**'
    branches: [ master ]

env:
  build: '${{ github.workspace }}/build'

jobs:
  build:
    name: Microsoft C++ Code Analysis
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B ${{ env.build }}

      - name: Run Microsoft Visual C++ Analysis
        id: run-analysis
        uses: microsoft/msvc-code-analysis-action@v0.0.1
        with:
          cmakeBuildDirectory: ${{ env.build }}
          ignoredTargetPaths: ${{ github.workspace }}/tests
          ruleset: '${{ github.workspace }}/infra/Analysis.ruleset'

      - name: Upload SARIF as an Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sarif-file
          path: ${{ steps.run-analysis.outputs.sarif }}
          if-no-files-found: error

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.run-analysis.outputs.sarif }}
