name: Docs

on:
  push:
    paths:
      - 'doc/**'
      - '.github/workflows/docs.yaml'
    branches: [ main ]
  pull_request:
    paths:
      - 'doc/**'
      - '.github/workflows/docs.yaml'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Ubuntu

    steps:
    - uses: actions/checkout@v2

    - name: Install GCC, CMake
      run: |
        # https://github.com/actions/runner-images/issues/7192
        echo 'APT::Get::Always-Include-Phased-Updates "false";' | sudo tee /etc/apt/apt.conf.d/99-phased-updates
        sudo apt-get update && sudo apt-get -y upgrade --fix-missing
        sudo apt-get install build-essential cmake texlive texlive-latex-extra

    - name: Configure & Build CMake
      uses: lukka/run-cmake@v3
      with:
        buildDirectory: build
        cmakeAppendedArgs: -DBUILD_DOC=ON
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        buildWithCMakeArgs: --target doc
