name: Mac-Build

on:
  push:
    paths-ignore:
      - 'doc/**'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - 'doc/**'
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: mkdir build && cmake -Bbuild

    - name: Build project
      run: make -C build
