name: MSVC

on:
  push:
    paths-ignore:
      - 'doc/**'
    branches: [ main ]
  pull_request:
    paths-ignore:
      - 'doc/**'
    branches: [ main ]

jobs:
  build:
    name: MSVC Preview -x- ${{ matrix.config }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Install MSVC Build Tools Preview
        shell: pwsh
        run: |
          $url = "https://aka.ms/vs/18/insiders/vs_buildtools.exe"
          Invoke-WebRequest -Uri $url -OutFile "$env:TEMP\vs_buildtools.exe" -UseBasicParsing
          $process = Start-Process -Wait -PassThru -FilePath "$env:TEMP\vs_buildtools.exe" `
            -ArgumentList "--quiet  --wait --norestart --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows11SDK.26100 --add Microsoft.VisualStudio.Component.VC.CMake.Project --includeRecommended"
          $exitCode = $process.ExitCode
          Write-Output "VS installer exit code: $exitCode"
          if ($exitCode -notin 0,3010,3015) { throw "VS Installer failed: $exitCode" }

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: '18'

      - name: Configure
        shell: pwsh
        run: >
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Build
        shell: pwsh
        run: cmake --build build --parallel --config ${{ matrix.config }}

      - name: Test
        shell: pwsh
        run: ctest --test-dir build --output-on-failure
